### ISSUE TITLE
provide general 'how does datajoint compare to <X>' 

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-docs-original#13]
a good clarifying pointer for people comparison shopping between various systems, software, etc.

thinking X might be best addressed categorically with examples

such as:

`how does datajoint compare to a Laboratory Information System (LIMS, e.g: Alyx, mLIMS, etc)`

and:

`how does datajoint compare to a Object Relational Mapper (ORM, e.g: Django ORM, SQLAlchemy, etc)`

and so on..

**Comment by austin-hilberg** [comment]
@dimitri-yatsenko Did you intend to close this when you referenced it in your PR last month?

**Comment by dimitri-yatsenko** [comment]
This is addressed in the FAQ Section of the new documentation.  Let's close.
