### ISSUE TITLE
"Foreign key" should be called "dependency" throughout.

### ISSUE THREAD

**Issue by austin-hilberg** [datajoint/datajoint-docs-original#142]
(with few exceptions)

**Comment by austin-hilberg** [comment]
@dimitri-yatsenko Could you clarify when to use "foreign key" vs "dependency"?

**Comment by dimitri-yatsenko** [comment]
Dependency is the entire concept and the underlying mechanism: referential constraint and foreign key.

Foreign key is one component of makes the dependency.  The foreign key is the subset of attributes in the dependent table that references the primary key of the referenced table.  The foreign key also refers to the index on the dependent table that is created for fast lookup of rows by their foreign key values.
