### ISSUE TITLE
Query object EEG figure in wrong location.

### ISSUE THREAD

**Issue by austin-hilberg** [datajoint/datajoint-docs-original#161]
Needs to be closer to first reference.

**Comment by austin-hilberg** [comment]
@mahos In the `.rst`, the figure comes immediately after the text where it is introduced. In the Python PDF, the figure is several paragraphs later than it should be. However, the figure is where it should be in MATLAB. Is this a LaTeX issue?

**Comment by mahos** [comment]
I see what you're talking about - and yes, I think it has to do with LaTeX setup - let me look into it to see if that ordering issue can be fixed.
