### ISSUE TITLE
Renamed foreign key when defining a new table needs an example.

### ISSUE THREAD

**Issue by shenshan** [datajoint/datajoint-docs-original#185]
An example such as:

```
@schema
class ThisTable(dj.Manual):
...
(new_name) -> AnotherTable
...
```

**Comment by dimitri-yatsenko** [comment]
The syntax has changed.  The example above would now look like:

```python
@schema
class ThisTable(dj.Manual):
    definition = """
    ...
    -> AnotherTable.proj(new_name="old_id")
    ...
    """
```

However, I think the documentation already contains examples: https://docs-dev.datajoint.io/python/definition/10-Dependencies.html#renamed-foreign-keys

**Comment by shenshan** [comment]
Ok. Good to know. Thanks!
