### ISSUE TITLE
describe how to interact with Pandas from datajoint-python

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-docs-original#189]
See datajoint-python issue https://github.com/datajoint/datajoint-python/issues/459

**Comment by austin-hilberg** [comment]
https://github.com/datajoint/datajoint-python/issues/537

**Comment by austin-hilberg** [comment]
@dimitri-yatsenko Could you provide an example of the final syntax? There is a lot of back and forth discussion under the two related issues, and I don't see a definitive description of the ultimate implementation.

**Comment by dimitri-yatsenko** [comment]
The description is already provided in the doc strings of `fetch` and `insert`.  Restriction also accepts a `pandas.DataFrame` the same way it accepts record arrays.
