### ISSUE TITLE
Switch language could be a single click rather than a drop down menu

### ISSUE THREAD

**Issue by austin-hilberg** [datajoint/datajoint-docs-original#194]

**Comment by austin-hilberg** [comment]
Currently we only have two languages, so the drop down isn't really needed. Can "Switch version" simply be a one-click link?

**Comment by eywalker** [comment]
As we envision having multiple versions for each language in the near future, dropdown list will be most appropriate.

**Comment by austin-hilberg** [comment]
How long is "the near future"? It could save a lot of clicks in the meantime...
