### ISSUE TITLE
Auto-populate - Make: is make(self, key) correct syntax for MATLAB?

### ISSUE THREAD

**Issue by austin-hilberg** [datajoint/datajoint-docs-original#195]

**Comment by dimitri-yatsenko** [comment]
No, the current implementation uses `makeTuples`.   We should change it to `make` ASAP.

**Comment by austin-hilberg** [comment]
@dimitri-yatsenko Based on your comments in other issues, I believe this is an implementation issue rather than a documentation issue. Shall I close this?

**Comment by dimitri-yatsenko** [comment]
#206 and https://github.com/datajoint/datajoint-matlab/pull/139  fixes this
