### ISSUE TITLE
investigate api documentation integration tools (e.g pydoc & sphinx, etc)

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-docs-original#25]
python/pydoc: http://www.sphinx-doc.org/es/stable/ext/autodoc.html
matlab: https://github.com/sphinx-contrib/matlabdomain

**Comment by dimitri-yatsenko** [comment]
Any progress?

**Comment by ixcat** [comment]
this was filed for tracking, can take a look.

**Comment by dimitri-yatsenko** [comment]
Open if there is a specific need or issue.
