### ISSUE TITLE
Use one consistent example schema throughout documentation

### ISSUE THREAD

**Issue by austin-hilberg** [datajoint/datajoint-docs-original#61]
There should be a single example schema design used across all sections of the documentation.

**Comment by dimitri-yatsenko** [comment]
Not sure why this should be.  We can use several examples for different goals.  The university database is great for showing more complex designs and queries but does not have interesting calculations.

**Comment by austin-hilberg** [comment]
Oh, I thought this was your suggestion. I was going to begin to incorporate the university example into the Queries section.

**Comment by dimitri-yatsenko** [comment]
yes, we can use the university schema to illustrate queries and a different schema to illustrate computations, for example.

**Comment by austin-hilberg** [comment]
I think a single example design could be helpful, so that the concepts can build up as people read different sections, but if you disagree I can close the issue.

**Comment by dimitri-yatsenko** [comment]
It may or it may not.  I would use whatever works to accomplish the goals.

**Comment by dimitri-yatsenko** [comment]
Let's go ahead and introduce the university database to illustrate queries.
