### ISSUE TITLE
Describe the use of `dj.kill`

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-docs-original#70]

**Comment by austin-hilberg** [comment]
@dimitri-yatsenko Where should this go? It is listed in `admin.py`; should it go in the admin section, or maybe in setup?

**Comment by dimitri-yatsenko** [comment]
No, I think regular users should be able to do it.  The `admin` module contains admin functions that regular users must perform, not system administrators.  I would put it under distributed computation or job management.
