### ISSUE TITLE
Describe the use of `table.progress`

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-docs-original#71]

**Comment by austin-hilberg** [comment]
Is a description of the `display_progress` parameter to `populate` sufficient, or should there be additional discussion? I am not familiar with this method.

**Comment by dimitri-yatsenko** [comment]
In both, matlab and python, the `table.progress` method reports how many key_source entries have been populated and how many remain.  See the doc string for `autopopulate.progress` or `dj.AutoPopulate/progress`.

This is distinct from the `display_progress` keyword argument in `populate`.

**Comment by austin-hilberg** [comment]
Ah, I see. Thank you for the clarification.
