### ISSUE TITLE
Add restrictions by a collection, a mapping, a string, an AndList, and a Not.

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-docs-original#73]

**Comment by austin-hilberg** [comment]
@dimitri-yatsenko How would `A Boolean expression` be used in restriction? It is listed in the types of conditions from the previous draft of the documentation (below), but I do not see an equivalent in the paper. Is it simply the trivial case of all or none of the entities?
```
* another table
* a mapping, e.g. ``dict``
* an expression in a character string
* a collection of conditions, e.g. a ``list``
* a Boolean expression (``True`` or ``False``)
* an ``AndList``
* a ``Not`` object
* ```
