### ISSUE TITLE
Document the option `force=True` on Part table's drop and delete

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-docs-original#8]
Because it is not required for the master class to be an ancestor of the part table, you can fall into situations as seen in datajoint/datajoint-python#421 that requires you to delete/drop the part table directly. This is actually possible via `force=True` option but this is not documented explicitly.

**Comment by austin-hilberg** [comment]
@eywalker Does this only apply to Python? Dropping a part table by itself seemed to work without issue for me in MATLAB.
