### ISSUE TITLE
Explain use of dj for DataJoint

### ISSUE THREAD

**Issue by austin-hilberg** [datajoint/datajoint-docs-original#96]

**Comment by dimitri-yatsenko** [comment]
hm... Not sure what this means.  You mean just to say that by convention, we alias the package as `dj` when importing? 
```
import datajoint as dj
```
Yes, we should mention it maybe in the scheme create section.

**Comment by austin-hilberg** [comment]
Yes, this is in response to your PR comment:
```Do we explain somewhere that datajoint is typically aliased as dj when imported and that we use this convention throughout?```

**Comment by austin-hilberg** [comment]
It might be a good thing in the terminology section as well, because that's probably where people would look if they are confused by it.
