### ISSUE TITLE
Discussion of attribute definition with default value should include NULL 

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-docs-original#99]
Currently the documentation doesn't make it obvious what values are allowed as the value for the default value setting syntax (i.e. `attr1 = "val"`). A few concrete examples for different data types along with a specific explanation for `NULL` as a default value and its interpretation (i.e. basically, an optional attribute), should be mentioned.

**Comment by austin-hilberg** [comment]
@eywalker working on the `NULL` explanation now, but I'm not sure what you mean by `what values are allowed as the value for the default value setting syntax (i.e. attr1 = "val")` or `examples for different data types`

**Comment by dimitri-yatsenko** [comment]
Generally, default values are numbers or strings.  Even for dates, strings are used and should be included in quotes.  NULL is a special literal value and it does not need to be enclosed in quotes.  Another special value is CURRENT_DATETIME and it does not need enclosed in quotes either.
